version: 2

models:
  - name: source_data
    description: '{{ doc("table_source_data") }}'
    columns:
      - name: id
        type: integer
        description: A primary key for source data.
        tests:
          - unique
          - not_null
  - name: ref_source_data_one
    description: 'a sample table that referenced the other table'
    columns:
      - name: id
        type: int
        description: A primary key for source data.
        tests:
          - unique
          - not_null