version: 2

models:
  - name: asset_owners
    description: '{{ doc("asset_owners") }}'
    tests:
      - dbt_utils.equal_rowcount:
           compare_model: source('pilot_db','asset')
    columns:
      - name: asset_name
        type: varchar
        description: name.
        tests:
          - unique
          - not_null
      - name: owner_name
        type: varchar
        description: A name
  - name: user
    description: '{{ doc("user") }}'
    columns:
      - name: user_id
        type: int
        description: A primary key for source data.
        tests:
          - unique
          - not_null
      - name: name
        type: varchar
      - name: role
        type: varchar
      - name: asset_id
        type: int